#!/bin/bash
# Editor: Sam
# Ver: 1.4
# Syntax: dockerpack {root path of packages} <-v>
# -v : verbose


# Check whether the user has enter the parameter of path.
if [ -z $1 ]
then
    echo -e "\033[31mPlease enter the path of the dockerfile. \033[0m"
    exit 1
fi

# Check whether the path is existing.
#echo $2
if [ ! -d $1 ]
then 
    echo -e "\033[31mPlease enter a existing path or a directory. \033[0m"
    exit 2
fi

dockerfile_list=$(ls $1)
if [ -z "$dockerfile_list" ]
then
    echo -e "\033[31mThis is a blank directory.\033[0m"
    exit 3
fi

timestamp=$(date +"%s")
success=0
failure=0
error=0

cd $1
for a in $dockerfile_list
do
    cd $a
    if [ -e Dockerfile ]
    then
        if [ -z $2 ]
        then
            #echo "stage 1"
            image_id=$(docker images | grep $a | awk '{print $3}')
            docker rmi -f $image_id >> /tmp/dockerbuild.$timestamp
            docker build -t $(basename `pwd`):$(date +"%Y%m%d.%H%M%S") . >> /tmp/dockerbuild.$timestamp
        elif [ "$2" = "-v" ]
        then
            #echo "stage 2"
            image_id=$(docker images | grep $a | awk '{print $3}')
            docker rmi -f $image_id
            docker build -t $(basename `pwd`):$(date +"%Y%m%d.%H%M%S") .
        else
            echo -e "\033[31;1mErroneous parameter\033[0m"
        fi
        success=$(($success+1))
        if [ "$?" -ne 0 ]
        then 
            echo -e "\033[31mBuild failed!!!\033[0m"
            failure=$(($failure+1))
            cd ..
            continue
        fi
        cd ..
    else
        echo -e "\033[31mDockerfile doesn't exist in `pwd`.\033[0m"
        error=$(($error+1))
        cd ..
        continue
    fi
done
echo -e "\033[1;4mComplete!!!\033[0m"
if [ $success -ne 0 ]
then
    if [ "$2" != "-v" ]
    then
        echo -e "You could find the log emitted by docker during the packing in \033[1m/tmp/dockerbuild.$timestamp\033[0m"
    fi
fi
echo -e "\033[32;1mSuccess :    $success\033[0m"
echo -e "\033[35;1mFailure :    $failure\033[0m"
echo -e "\033[35;1mError   :    $error\033[0m"

